<?php
session_start();
unset($_SESSION["id"]);
unset($_SESSION["usuario"]);
unset($_SESSION["senha"]);
unset($_SESSION["listar_nc"]);
unset($_SESSION["importar_nc"]);
unset($_SESSION["exportar_nc"]);
unset($_SESSION["listar_ba"]);
unset($_SESSION["importar_ba"]);
unset($_SESSION["exportar_ba"]);
unset($_SESSION["listar_pg"]);
unset($_SESSION["importar_pg"]);
unset($_SESSION["exportar_pg"]);
unset($_SESSION["listar_ag"]);
unset($_SESSION["incluir_ag"]);
unset($_SESSION["editar_ag"]);
unset($_SESSION["apagar_ag"]);
header("location: index.php");
?>
